// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    exclude: ['**/dist/**', '**/lib/**', '**/node_modules/**'],
    globals: true,
    include: ['**/*.test.ts?(x)'],
  },
});
