// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

// E2E test configuration
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    clearMocks: false,
    exclude: ['**/dist/**', '**/build/**', '**/node_modules/**'],
    include: ['**/*-e2e-test.ts?(x)'],
    mockReset: true,
    restoreMocks: false,
  },
});
